[package]
name = "boot"
version = "0.1.0"
edition = "2021"

[lib]
name = "boot"
test = false
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tock-registers = "0.7"
cortex-a = "7.0"